== FeatureHub's pricing model

NOTE: For all recent prices please refer to our pricing table on https://featurehub.io/saas[this page]


FeatureHub pricing model consists of 2 components:

* Per seat charge - individual users and admin service accounts (fixed price - $7.99 per seat / per month)
* Usage charge (3 usage prices, per API request, TODO: insert price link here)

=== How does our pricing differ from others?

* Transparent pay-as-you-go pricing
* Full functionality access
* No hidden costs
* We charge per API request, not per MAU
* Our “per seat” price is low, so everyone in your team can be onboarded
* Pay for what you use. Usage charges directly correlate to your traffic volumes.


=== Usage types and charges

==== REST API charges
We price every request that customers make to our FH servers to get features. A client can choose how often you want to poll for new features. Because of its dynamic nature, we charge per request, e.g. as low as 0.0001(TODO) cent per request. When a request is made, a client will get all feature values for the requested environment for a single application.

==== Streaming API charges
Similar to the REST API requests, but instead we charge per SSE connection.

==== Test API charges
Similar to the REST API requests, your PUT requests to FH server (test SDK) will be counted and you will be charged per request. Note, usually when you write tests for FeatureHub, you would use a mix of REST API or Streaming API and Test API. Test API can be found here: TODO

=== Billing for FeatureHub Usage
To bill for the usage FeatureHub has integrated with Stripe. We use Stripe's own billing portal, so we do not hold or store any credit card information. Billing is done per month for the seats and for the usage requests as separate items. Seats are calculated on pro rata basis. FeatureHub also offers 30 days of free trial, where customers won't be charged and are not required to provide any credit card details.

=== Where can I view my current spent?
You are able to view your current usage on the Billing page (with super admin permissions).

=== Can I set a limit on the requests?
Yes, you can set limits on maximum requests you are expecting per billing month/period. When you reach the limit, FeatureHub will continue to serve your features, however you will not be able to update them.

=== How do you charge if I do not use FeatureHub dashboard and use programmatic access to the FeatureHub's Management Repository API via FeatureHub ADK?

To be able to use Management repository API, you need to create Admin Service Account which will be counted towards a “seat” charge. For example, if you create 2 Admin service accounts - one for the non-production environments permissions and the other for the production environments - you will be charged for 2 seats.

=== Why is FeatureHub not charging per MAU?
Every MAU is not “worth” the same money to a customer - a MAU that spends 10 minutes on their site is not of the same worth as one that spends 2 weeks on the site, and shouldn’t cost the same amount
We don’t have graduations - a single seat company with 2000 MAUs is possible on FH, and not on Launch Darkley, for example - you have to be Pro user at a higher per seat charge.








