= FeatureHub SaaS pricing model

NOTE: For all recent prices please refer to our pricing table on https://featurehub.io/pricing[this page]


FeatureHub pricing model consists of 2 components:

* Per seat charge - individual users and admin service accounts (fixed price per seat / per month)
* Metered usage charge for API requests - Streaming, REST or Test APIs (price per batch of 10,000 requests)

== How does our pricing differ from others?

* Full functionality access
* No hidden costs
* Low “per seat” price, we encourage everyone in your team to have access
* Pay for what you use. Metered usage charges directly correlate to your traffic volumes.

== Seats / users pricing (paid in advance)
We price every seat per month, either regular user or Admin Service Account, e.g. if you have 25 seats in your organization, you will pay `25 * seat price` as soon as you subscribe to our paid service. You are billed for the upcoming billing period in advance. Pricing is pro-rated, if you add or remove users, the relevant amount will be adjusted in your next invoice together with your next billing period charge.

== Metered usage types and pricing (pay-as-you-go)

=== REST API pricing
We price every request that customers make to our FH servers to get features and their values. You can choose how often you want to poll for new features. Because of its dynamic nature, we charge per request. When a request is made, a client will get all feature values for the requested environment for a single application (which is defined by the API key).
`GET request for /features?apiKey=`

=== Streaming API pricing
Similar to the REST API requests, but instead we charge per SSE connection request.
SSE connection initiated via GET request to `/features/{apiKey}` and reconnects automatically every 60 seconds. Every reconnect is counted towards charges as 1  request.

NOTE: SSE connection can only be made with client evaluated API keys and not supported with server evaluated API keys.

=== Test API pricing
Similar to the REST API requests, your PUT requests to the FH server https://docs.featurehub.io/featurehub/latest/sdks.html#_test_automation_support[via SDK Test Client] will be counted and you will be charged per request. Note, when you write tests for FeatureHub, you would use a mix of REST API or Streaming API and Test API. There is also an option to use Admin SDK API (ADK) to control feature states.
`PUT request for `/features?apiKey=`

More info on feature retrieval  https://docs.featurehub.io/featurehub/latest/sdks.html#_receiving_feature_updates[here]

== Billing for FeatureHub with Stripe
To bill for the paid plan FeatureHub has integrated with Stripe. We use Stripe's own billing portal, so we do not hold or store any credit card information in the FeatureHub platform itself. Billing is done per month for the seats and for the usage requests as separate price items for each type. Seats are calculated on pro rata basis. FeatureHub also offers 30 days of free trial, where customers won't be charged and are not required to provide any credit card details. Once you sign up for paid plan, the free trial will stop immediately.

== Managing subscription with Stripe
You can sign up for the paid plan at any time before your free trial expires. Once you sign up you will become an owner of the subscription, meaning only you will be able to manage it in your organisation. We will be adding a functionality in the future to transfer a subscription to another user in case you leave an organisation.

== Where can I view my current spent?
You are able to view your current usage on the Billing page (with super admin permissions).

== Can I set a limit on the requests?
If you are looking for a way to limit the requests or reduce your requests, you can set limits on when to stop polling or streaming updates, e.g. once you hit 50,000 requests - stop further polling or streaming requests. This setting is per billing month/period. Note, when you reach the limit, FeatureHub will continue to serve your features when your clients or server reconnect, however subsequent polling and streaming updates won't be performed. By using this setting you can reduce the number of requests/connections. But bear in mind once connection is made, a client won't be receiving real-time updates.

== How long is the free trial?
Free trial is available per organization for 30 days once an organization is created. Free trial ends either after 30 days or as soon as organization admin signs up for a paid plan.

== Will you charge a fee if I do not use FeatureHub dashboard and use programmatic access to the FeatureHub's Management Repository API via FeatureHub ADK?

To be able to use Management repository API, you need to create Admin Service Account which will be counted towards a “seat” charge. For example, if you create 2 Admin service accounts - one for the non-production environments permissions and the other for the production environments - you will be charged for 2 seats.









