= FeatureHub's pricing model

NOTE: For all recent prices please refer to our pricing table on https://featurehub.io/saas[this page]


FeatureHub pricing model consists of 2 components:

* Per seat charge - individual users and admin service accounts (fixed price - $7.99 per seat / per month)
* Metered usage charge (3 usage prices, per API request, TODO: insert price link here)

== How does our pricing differ from others?

* Transparent pay-as-you-go pricing
* Full functionality access
* No hidden costs
* Metered price per API request
* Reasonable “per seat” price, we encourage everyone in your team to have access
* Pay for what you use. Metered usage charges directly correlate to your traffic volumes.

== Seats / users pricing
We price every seat per month, either user or Admin service account, e.g. if you have 25 seats in your organization, you will pay `25 * seat price` at the end of your billing period. Pricing is pro-rated, so if you add or remove users, this will be taken into account.

== Pay-as-you-go usage types and pricing

=== REST API pricing
We price every request that customers make to our FH servers to get features. A client can choose how often you want to poll for new features. Because of its dynamic nature, we charge per request, e.g. as low as 0.0001(TODO) cent per request. When a request is made, a client will get all feature values for the requested environment for a single application.

=== Streaming API pricing
Similar to the REST API requests, but instead we charge per SSE connection.

=== Test API pricing
Similar to the REST API requests, your PUT requests to FH server (test SDK) will be counted and you will be charged per request. Note, usually when you write tests for FeatureHub, you would use a mix of REST API or Streaming API and Test API. Test API can be found here: TODO

== Billing for FeatureHub with Stripe
To bill for the usage FeatureHub has integrated with Stripe. We use Stripe's own billing portal, so we do not hold or store any credit card information. Billing is done per month for the seats and for the usage requests as separate items. Seats are calculated on pro rata basis. FeatureHub also offers 30 days of free trial, where customers won't be charged (unless you sign up for paid plan, the free trial will stop) and are not required to provide any credit card details.

== Managing subscription with Stripe
You can sign up for the paid plan at any time before your free trial expires. Once you sign up you will become an owner of the subscription, meaning only you will be able to manage it in your organisation. We will be adding a functionality in the future to transfer a subscription to another user in case you leave an organisation.

== Where can I view my current spent?
You are able to view your current usage on the Billing page (with super admin permissions).

== Can I set a limit on the requests?
Yes, you can set limits on maximum requests you are expecting per billing month/period. When you reach the limit, FeatureHub will continue to serve your features, however you will not be able to update them.

== How do you charge if I do not use FeatureHub dashboard and use programmatic access to the FeatureHub's Management Repository API via FeatureHub ADK?

To be able to use Management repository API, you need to create Admin Service Account which will be counted towards a “seat” charge. For example, if you create 2 Admin service accounts - one for the non-production environments permissions and the other for the production environments - you will be charged for 2 seats.

== Why is FeatureHub not charging per MAU?
Every MAU is not “worth” the same money to a customer - a MAU that spends 10 minutes on their site is not of the same worth as one that spends 2 weeks on the site, and shouldn’t cost the same amount
We don’t have graduations - a single seat company with 2000 MAUs is possible on FH, and not on Launch Darkley, for example - you have to be Pro user at a higher per seat charge.








